### ISSUE TITLE
Script doesn't work with PHP 8.1

### ISSUE THREAD

**Issue by s22-tech** [erlandmuchasaj/emcmsrental#2]
Trying to run this under 8.1 gives me the following errors:

```
[php:error] [pid 3198] [client 127.0.0.1:50099] PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /usr/local/var/www/emcms-rental/lib/Cake/Model/Behavior/ContainableBehavior.php on line 309

[php:error] [pid 3198] [client 127.0.0.1:50099] PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /usr/local/var/www/emcms-rental/lib/Cake/View/Helper/FormHelper.php on line 2063
```
Once I fixed those, I then got this error:
```
Fatal error: Uncaught Error: Unknown named parameter $subject in /www/emcms-rental/lib/Cake/Utility/ObjectCollection.php:129 

Stack trace: 
#0 /www/emcms-rental/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('initialize') 
#1 /www/emcms-rental/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent)) 
#2 /www/emcms-rental/lib/Cake/Error/ExceptionRenderer.php(158): Controller->startupProcess() 
#3 /www/emcms-rental/lib/Cake/Error/ExceptionRenderer.php(95): ExceptionRenderer->_getController(Object(FatalErrorException)) 
#4 /www/emcms-rental/lib/Cake/Error/ErrorHandler.php(126): ExceptionRenderer->__construct(Object(FatalErrorException)) 
#5 /www/emcms-rental/lib/Cake/Error/ErrorHandler.php(269): ErrorHandler::handleException(Object(FatalErrorException)) 
#6 /www/emcms-rental/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Uncaught Error:...', '/...', 129) 
#7 /www/emcms-rental/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Uncaught Error:...', '/...', 129, Array) 
#8 /www/emcms-rental/lib/Cake/Core/App.php(943): App::_checkFatalError() 
#9 [internal function]: App::shutdown() 
#10 {main} thrown in /www/emcms-rental/lib/Cake/Utility/ObjectCollection.php on line 129
```
I've never worked with Cake, so I don't know how far I can go.  Are you planning on updating this script for newer versions of PHP?  Thanks.

**Comment by erlandmuchasaj** [comment]
Hello @s22-tech, the script was built with PHP 5.6 and later 7.1  so it can be configured up to that point. 

Currently, it is not in my roadmap to update the script because it would take too much effort since it needs also to update the core. 

anyone is welcomed to update it and make a pull request. 

thanks.
